spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.202.81:3306/yto?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: XA&YtoOverseas
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logSlowSql: true

  #热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: WEB-INF/**

  #日志多彩输出
  output:
    ansi:
      enabled: detect


  #thymeleaf默认配置(如需修改再改)
  #thymeleaf:
    #cache: true
    #check-template: true
    #check-template-location: true
    #servlet:
      #content-type: text/html
    #encoding: UTF-8
    #mode: HTML
    #prefix: classpath:/templates
    #suffix: .html
  #redis配置
  redis:
    #redis数据库索引
    database: 0
    host: 192.168.202.81
    port: 6379
    password:

  #设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**

  #freemarker配置(默认)
  freemarker:
    request-context-attribute: request


#mybatis配置
mybatis:
  #配置mapper xml文件所在路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #config-location: classpath:mapper/*Mapper.xml
  #配置映射类所在包名
  type-aliases-package: yto.ceng.paractise.paractise.sample.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志级别配置
logging:
  level:
    root: info
